version: "3.9"

services:
  api:
    container_name: api_kimoveis
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "yarn typeorm migration:run -d ./src/data-source && yarn dev"
    volumes:
      - .:/app

  postgres:
    container_name: db_kimoveis
    image: postgres:latest
    ports:
      - 5431:5432
    env_file:
      - .env